<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var $block \Magento\Catalog\Block\Product\View */
?>
<?php $_product = $block->getProduct(); ?>
<?php $buttonTitle = __('Add to Cart'); ?>
<?php if ($_product->isSaleable()): ?>
<div class="box-tocart">
    <div class="fieldset">
        <?php if ($block->shouldRenderQuantity()): ?>
        <div class="field qty">
            <label class="label" for="qty"><span><?= /* @escapeNotVerified */ __('Qty') ?></span></label>
            <div class="control">
                <input type="number"
                       name="qty"
                       id="qty"
                       value="<?= /* @escapeNotVerified */ $block->getProductDefaultQty() * 1 ?>"
                       title="<?= /* @escapeNotVerified */ __('Qty') ?>"
                       class="input-text qty"
                       data-validate="<?= $block->escapeHtml(json_encode($block->getQuantityValidators())) ?>"
                       />
            </div>
        </div>
        <?php endif; ?>
        <div class="actions">
            <button type="submit"
                    title="<?= /* @escapeNotVerified */ $buttonTitle ?>"
                    class="cta action primary tocart"
                    formaction="add-to-cart"
                    onclick="document.getElementByClass("get-quote").style.display = "none";"
                    id="product-addtocart-button">
                <span><?= /* @escapeNotVerified */ $buttonTitle ?></span>
            </button>
            <input type="checkbox" id="quote-toggle" class="quote-toggle-checkbox">
            <label for="quote-toggle" class="action primary quote">
                <span>get a quote</span>
            </label>
            <div class="get-quote">
                <form action="#"></form>
                <form action="#"></form>
                <form class="form contact" 
                    action="<?php echo $this->getUrl('contact/index/post'); ?>"
                    id="contact-form"
                    method="post"
                    data-hasrequired="<?= $block->escapeHtmlAttr(__('* Required Fields')) ?>"
                    data-mage-init='{"validation":{}}'>
                    <fieldset class="fieldset">
                        <div class="field note no-label"><?= $block->escapeHtml(__('Please send us a message, we will get back to you as soon as possible.')) ?></div>
                        <div class="field name required">
                            <label class="label" for="name"><span><?= $block->escapeHtml(__('Name')) ?></span></label>
                            <div class="control">
                                <input name="name" id="name" title="<?= $block->escapeHtmlAttr(__('Name')) ?>" value="<?= $block->escapeHtmlAttr($this->helper('Magento\Contact\Helper\Data')->getPostValue('name') ?: $this->helper('Magento\Contact\Helper\Data')->getUserName()) ?>" class="input-text" type="text" />
                            </div>
                        </div>
                        <div class="field email required">
                            <label class="label" for="email"><span><?= $block->escapeHtml(__('Email')) ?></span></label>
                            <div class="control">
                                <input name="email" id="email" title="<?= $block->escapeHtmlAttr(__('Email')) ?>" value="<?= $block->escapeHtmlAttr($this->helper('Magento\Contact\Helper\Data')->getPostValue('email') ?: $this->helper('Magento\Contact\Helper\Data')->getUserEmail()) ?>" class="input-text" type="email" />
                            </div>
                        </div>
                        <div class="field telephone">
                            <label class="label" for="telephone"><span><?= $block->escapeHtml(__('Phone Number')) ?></span></label>
                            <div class="control">
                                <input name="telephone" id="telephone" title="<?= $block->escapeHtmlAttr(__('Phone Number')) ?>" value="<?= $block->escapeHtmlAttr($this->helper('Magento\Contact\Helper\Data')->getPostValue('telephone')) ?>" class="input-text" type="text" />
                            </div>
                        </div>
                        <div class="field product required">
                            <label class="label" for="product"><span><?= $block->escapeHtml(__('Product')) ?></span></label>
                            <div class="control">
                                <input name="product" id="product" title="<?= $block->escapeHtmlAttr(__('Product')) ?>" value="<?= $_product->getName() ?>" class="input-text" type="text" data-validate="{required:false}"/>
                            </div>
                        </div>
                        <div class="field comment required">
                            <label class="label" for="comment"><span><?= $block->escapeHtml(__('What’s on your mind?')) ?></span></label>
                            <div class="control">
                                <textarea name="comment" id="comment" title="<?= $block->escapeHtmlAttr(__('What’s on your mind?')) ?>" class="input-text" cols="5" rows="3"><?= $block->escapeHtml($this->helper('Magento\Contact\Helper\Data')->getPostValue('comment')) ?></textarea>
                            </div>
                        </div>
                        <?= $block->getChildHtml('form.additional.info') ?>
                    </fieldset>
                    <div class="actions-toolbar">
                        <div class="primary">
                            <input type="hidden" name="hideit" id="hideit" value="" />
                            <button type="submit" 
                                    title="<?= $block->escapeHtmlAttr(__('Submit')) ?>" 
                                    class="action submit primary">
                                <span><?= $block->escapeHtml(__('Submit')) ?></span>
                            </button>
                        </div>
                    </div>
                </form>

            </div>
            <button class= "action primary">
                <span>get details</span>
            </button>
            <?= $block->getChildHtml('', true) ?>
        </div>
        
    </div>
</div>
<?php endif; ?>
<script type="text/x-magento-init">
    {
        "#product_addtocart_form": {
            "Magento_Catalog/js/validate-product": {}
        }
    }

    
</script>
