<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/**
 * Product additional attributes template
 *
 * @var $block \Magento\Catalog\Block\Product\View\Attributes
 */

    $_helper = $this->helper('Magento\Catalog\Helper\Output');
    $_product = $block->getProduct();

    
?>


<div class="tabs tabs--column">
    <ul id="myTab" class="nav-tabs--column nav nav-tabs flex-column ">
        <li class="nav-item nav-item--column">
            <a id="product-tab" class="nav-link active" href="#product" data-toggle="tab">
                <span>
                    product
                </span>
            </a>
        </li>
        <li class="nav-item nav-item--column">
            <a id="packaging-tab" class="nav-link" href="#packaging" data-toggle="tab">
                <span>
                    packaging
                </span>
            </a>
        </li>
        <li class="nav-item nav-item--column">
            <a id="documents-tab" class="nav-link" href="#documents" data-toggle="tab">
                <span>
                    documents
                </span>
            </a>
        </li>
    </ul>
    <div id="myTabContent" class="tab-content tab-content--column">
        <div id="product" class="tab-pane fade show active">
             <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel" data-interval="5000">
                <ol class="carousel-indicators">
                    <li class="active" data-target="#carouselExampleIndicators" data-slide-to="0"></li>
                    <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
                </ol>
                <div class="carousel-inner">
                    <div class="carousel-item active">
                        <img class="d-block w-100" src="<?php echo $this->helper('Magento\Catalog\Helper\Image')->init($_product, 'pack_img1')->setImageFile($_product->getCustomAttribute( 'pack_img1' )->getValue())->getUrl(); ?>" />
                    </div>
                    <div class="carousel-item">
                        <img class="d-block w-100" src="<?php echo $this->helper('Magento\Catalog\Helper\Image')->init($_product, 'pack_img2')->setImageFile($_product->getCustomAttribute( 'pack_img2' )->getValue())->getUrl(); ?>" />
                    </div>
                </div>
                <a class="carousel-control-prev" href="#carouselExampleIndicators" data-slide="prev">
                    <span class="carousel-control-prev-icon"></span>
                    <span class="sr-only">Previous</span>
                </a>
                <a class="carousel-control-next" href="#carouselExampleIndicators" data-slide="next">
                    <span class="carousel-control-next-icon"></span>
                    <span class="sr-only">Next</span>
                </a>
            </div>
        </div>
        <div id="packaging" class="tab-pane fade">...</div>
        <div id="documents" class="tab-pane fade">...</div>
    </div>
</div>