<div class="tabs">
    <ul id="myTab" class="nav nav-tabs flex-column">
        <li class="nav-item">
            <a id="home-tab" class="nav-link active" href="#home" data-toggle="tab">
                <span>
                    supplier
                </span>
            </a>
        </li>
        <li class="nav-item">
            <a id="profile-tab" class="nav-link" href="#profile" data-toggle="tab">
                <span>
                    product
                </span>
            </a>
        </li>
        <li class="nav-item">
            <a id="contact-tab" class="nav-link" href="#contact" data-toggle="tab">
                <span>
                    services
                </span>
            </a>
        </li>
    </ul>
    <div id="myTabContent" class="tab-content">
        <div id="home" class="tab-pane fade show active">
            <h3 class="tab-content--title">
                Find out our latest supplier, a really nice guy
            </h3>
            <p class="tab-content--content">
                Lorem ipsum dolor sit amet consectetur adipisicing elit. Ab minus distinctio cupiditate obcaecati, fugiat exercitationem
                deleniti doloremque doloribus! Quidem nesciunt velit fuga, mollitia ipsam neque cumque repudiandae! Corporis,
                harum illo.
            </p>
        </div>
        <div id="profile" class="tab-pane fade">...</div>
        <div id="contact" class="tab-pane fade">...</div>
    </div>
</div>