<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/**
 * Product additional attributes template
 *
 * @var $block \Magento\Catalog\Block\Product\View\Attributes
 */
?>
<?php
    $_helper = $this->helper('Magento\Catalog\Helper\Output');
    $_product = $block->getProduct();
    $_pricingHelper = $this->helper(\Magento\Framework\Pricing\Helper\Data::class);
?>
<div class="product-info-custom--names">
    <span class="product-info-custom--names__full-name">
        <?= $_product->getName() ?>
    </span>
    <span class="product-info-custom--names__latin-name">
        <?= $_product->getLatinNames() ?>
    </span>
    <span class="product-info-custom--names__id">
        ref: <?= $_product->getUniqueId() ?>
    </span>    
</div>

<div class="product-info-custom--description">
    <span class="product-info-custom--description__content">
        <?= $_product->getShortDescr() ?>
    </span>
</div>

<div class="product-info-custom--prices">
    <div class="product-info-custom--prices__item1">
        <?= $_pricingHelper->currency($_product->getUnitPrice(), true, false); ?>
    </div>
    <div class="product-info-custom--prices__item2">
        <?= $_product->getIncoterms() ?>
    </div>
    <div class="product-info-custom--prices__item3">
        <?= $_pricingHelper->currency($_product->getPerkgPrice(), true, false); ?>
    </div>
</div>

<div class="product-info-custom--details">
    <div class="product-info-custom--details__origin">
        <?= $_product->getOrigin() ?>
    </div>
    <div class="product-info-custom--details__freezing">
        <?= $_product->getFreezingProcess() ?>
    </div>
    <div class="product-info-custom--details__packaging">
        <?= $_product->getPackagingDetails() ?>
    </div>
    <div class="product-info-custom--details__process">
        <?= $_product->getIndusProcess() ?>
    </div>
    <div class="product-info-custom--details__supplier">
        <?= $_product->getSupplierName() ?>
        <?= $_product->getSupplierId() ?>
    </div>
</div>